#!/bin/sh

# This script deploys CSI Driver for Intel® Rack Scale Design(Intel® RSD)
# on the fully configured Kubernetes node.

set -e

: "${RSD_NODE_ID:=1}"

echo "- setting label csi-driver=csi-intel-rsd"
kubectl label node --overwrite $(hostname | tr '[:upper:]' '[:lower:]') csi.intel.com/rsd-node=$RSD_NODE_ID

echo "- deploying CSI driver"
kubectl create -f driver.yaml
