#!/bin/sh

# This script deploys CSI Driver for Intel® Rack Scale Design(Intel® RSD)
# on the fully configured Kubernetes node.

set -e

echo "- setting label csi-driver=csi-intel-rsd"
kubectl label node --overwrite $(hostname | tr '[:upper:]' '[:lower:]') csi-driver=csi-intel-rsd

echo "- deploying CSI driver"
kubectl create -f driver.yaml
