#!/bin/sh

echo "- removing csi-driver label"
kubectl label node $(hostname | tr '[:upper:]' '[:lower:]') csi.intel.com/rsd-node-

echo "- removing plugin components"
kubectl delete statefulset csi-intel-rsd-driver
kubectl delete service csi-intel-rsd-driver
